# Generated by Django 2.0.7 on 2018-07-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='project_screenshots/')),
                ('description', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Description')),
                ('year_development', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year development')),
                ('optional_url', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
